DELETE FROM BOOKS;
DELETE FROM GENRES;

INSERT INTO GENRES (NAME) VALUES ('Povest');
INSERT INTO GENRES (NAME) VALUES ('Skazka');

INSERT INTO BOOKS (NAME, AUTHOR, GENRE_ID) VALUES ('Book1Name', 'Pushkin', 1);
INSERT INTO BOOKS (NAME, AUTHOR,  GENRE_ID) VALUES ('Book2Name', 'Lermontov', 2);
INSERT INTO BOOKS (NAME, AUTHOR, GENRE_ID) VALUES ('Book3Name', 'Gogol', 1);
