DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;


CREATE TABLE IF NOT EXISTS BOOKS (
  ID				  INT PRIMARY KEY AUTO_INCREMENT,
  AUTHOR      VARCHAR (50),
  NAME		    VARCHAR(50),
  GENRE_ID		INT
);

CREATE TABLE  IF NOT EXISTS GENRES (
  ID    			INT PRIMARY KEY AUTO_INCREMENT,
  NAME		    VARCHAR(50)
);

ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE CASCADE;